### ISSUE TITLE
Deserialized datetimes should be timezone-aware and UTC.

### ISSUE THREAD

**Issue by ses4j** [marcosschroh/dataclasses-avroschema#337] opened 2023-06-02 14:36 UTC
**Describe the bug**
According to the Avro spec, `timestamp-millis` are based on the unix epoch and UTC:

> The timestamp-millis logical type represents an instant on the global timeline, independent of a particular time zone or calendar, with a precision of one millisecond.

As a result, I would expect the deserialize routine to return timezone-aware UTC datetimes, but instead I get naive ones.

**To Reproduce**

Serialize a timezone-aware, UTC datetime.datetime, then deserialize it, and compare the `timestamp()` of each - unless your local timezone is UTC, they will not match.

**Expected behavior**

For the above to match, and since we know timestamp-millis are UTC, they should return as such.

**Comment by marcosschroh** [comment] 2023-06-14 18:42
Thanks for reporting this bug @ses4j. I will try to fix it asap

**Comment by marcosschroh** [comment] 2023-06-16 09:57
Hi @ses4j 

I took a close look to this issue and I can not reproduce it. The `deserialization` always returns `aware` datetime objects regardless whether the serialization was with naive or aware `datetime`

```python
import dataclasses

from dataclasses_avroschema import AvroModel,
from datetime import datetime, timezone

@dataclasses.dataclass
class Event(AvroModel):
    start: datetime
    end: datetime

start = datetime.utcnow().replace(tzinfo=timezone.utc)
end = datetime.utcnow()

event = Event(start=start, end=end)
print(f"The event {event}")

# The event Event(start=datetime.datetime(2023, 6, 16, 9, 41, 14, 336938, tzinfo=datetime.timezone.utc), end=datetime.datetime(2023, 6, 16, 9, 41, 14, 336953))

deserialized_event_dict = Event.deserialize(event.serialize(), create_instance=False)
deserialized_event = Event.deserialize(event.serialize())

print(deserialized_event_dict)
# {'start': datetime.datetime(2023, 6, 16, 9, 41, 14, 336000, tzinfo=datetime.timezone.utc), 'end': datetime.datetime(2023, 6, 16, 7, 41, 14, 336000, tzinfo=datetime.timezone.utc)}

print(deserialized_event)
# Event(start=datetime.datetime(2023, 6, 16, 9, 41, 14, 336000, tzinfo=datetime.timezone.utc), end=datetime.datetime(2023, 6, 16, 7, 41, 14, 336000, tzinfo=datetime.timezone.utc))
```

As the code shows is works properly in the sense that it always returns aware datetime. However, there is a mismatch with the microseconds and I think it is a bug in `fastavro`

Which  `dataclasses-avroschema` and `fastavro` versions are you using?

**Comment by marcosschroh** [comment] 2023-06-19 10:15
Closing this issue because I can not reproduce it. In all cases `aware` datetime object are generated after deserialize an event as the previous example shows.

For future reference: As avro datetime (`timestamp-millis`) does not include microseconds precision it loses the microseconds, this is why the previous example we see the discrepancy. For microseconds precision we should use `types.DateTimeMicro`

**Closed by marcosschroh** 2023-06-19 10:15 UTC
