### ISSUE TITLE
avro_schema method does not respect original ordering of unions or enums

### ISSUE THREAD

**Issue by robbertvanwaveren** [marcosschroh/dataclasses-avroschema#413] opened 2023-09-07 13:55 UTC
**Describe the bug**
The ordering in enums and unions is directly used to serialize into the proper bytes, just like the ordering of fields.
However it seems ordering is not respected.

**To Reproduce**

Generate a model from the following avro schema and use the `avro_schema` method to retrieve back the schema. I expect the fields, symbols and types in their arrays to remain ordered exactly the same. If not, the resulting avro will not be binary compatible with the original schema.

```
{
  "type": "record",
  "name": "TestModel",
  "fields": [
    {
      "name": "enum_field",
      "type": {
        "type": "enum",
        "name": "SomeEnum",
        "symbols": [
          "a",
          "A",
          "B",
          "b"
        ],
        "default": "Unknown"
      }
    },
    {
      "name": "optional_field",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
```

However it seems enum symbols are ordered by casing and union types are ordered randomly.

**Expected behavior**
See above

**Comment by marcosschroh** [comment] 2023-09-07 14:39
I can not reproduce this issue. 

The schema is wrong, as the default `Unknown` is not include in the `symbols`. In any case if you change to a proper default the generated model matches with the schema.

schema:

```python
from dataclasses_avroschema import ModelGenerator

model_generator = ModelGenerator()

schema = {
  "type": "record",
  "name": "TestModel",
  "fields": [
    {
      "name": "enum_field",
      "type": {
        "type": "enum",
        "name": "SomeEnum",
        "symbols": [
          "a",
          "A",
          "B",
          "b"
        ],
        "default": "a"
      }
    },
    {
      "name": "optional_field",
      "type": [
        "null",
        "string"
      ],
      "default": None
    }
  ]
}

result = model_generator.render(schema=schema)

print(result)
```

generates:

```python
from dataclasses_avroschema import AvroModel
import dataclasses
import enum
import typing


class SomeEnum(enum.Enum):
    A = "A"
    B = "B"
    a = "a"
    b = "b"


@dataclasses.dataclass
class TestModel(AvroModel):
    enum_field: SomeEnum = SomeEnum.A
    optional_field: typing.Optional[str] = None
```

Then getting the schema matches the initial one:

```python
print(TestModel.avro_schema_to_python())

{'type': 'record', 'name': 'TestModel', 'fields': [{'name': 'enum_field', 'type': {'type': 'enum', 'name': 'SomeEnum', 'symbols': ['A', 'B', 'a', 'b']}, 'default': 'A'}, {'name': 'optional_field', 'type': ['null', 'string'], 'default': None}]}
```

Are you using the latest version @robbertvanwaveren ?

**Comment by marcosschroh** [comment] 2023-09-08 08:19
Closing it because it is not reproducible

**Closed by marcosschroh** 2023-09-08 08:19 UTC

**Comment by marcosschroh** [comment] 2023-09-12 09:36
Ah I see @robbertvanwaveren

Working in the fix
